<?php

namespace App\Repository;

/**
 * EmailTemplateDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailStatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMaxRow() {
        return $this->getEntityManager()
            ->createQuery('SELECT max(e.id) FROM App:EmailStatus e')
            ->getSingleScalarResult();
    }
}