<?php

namespace App\Repository;

/**
 * LinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenderNameRepository extends \Doctrine\ORM\EntityRepository
{
    public function genderCheck($sizecnt) {
        $conn = $this->getEntityManager()->getConnection();
        $conn->getConfiguration()->setSQLLogger(null);
        //selecting only emails that were not checked within last 24 hours
        
        $qb0 = $this->getEntityManager()->createQueryBuilder();
        $qb0-> select('check')
            -> from('App\Entity\GenderName', 'check')
            -> where('s.firstname = check.firstname');
        /*primary query to select users for future campaigns*/
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb -> select('s')
            -> from('App\Entity\SubscriberDetails', 's')
            -> where($qb->expr()->not($qb->expr()->exists($qb0->getDQL())))
            /*-> orderBy('s.firstname', 'DESC')*/
            -> setMaxResults($sizecnt);
        return $qb->getQuery() ->getResult();
    }
}
