#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
controllers:
    resource: '../src/Controller/'
    type:     annotation
newpubcampaign:
    path:       /{_locale}/newpubcampaign
    controller: App\Controller\PublisherController::emailcampaignsAction
    requirements:
        _locale: en|ru|de
logout:
    path: /logout

admin:
    path: /{slug}
    defaults:
        _controller: App\Controller\FrontEndController::index